# 3 - Vector Multiplications
- 3.1 Vector dot product: Algebra
- 3.2 Dot product properties
- 3.3 Vector dot product: Geometry
- 3.4 Algebra and geometry
- 3.5 Linear weighted combinations
- 3.6 The outer product
- 3.7 Hadamard multiplication
- 3.8 Cross product
- 3.9 Unit vectors
- 3.10 Exercises
- 3.11 Answers
- 3.12 Code challenges
- 3.13 Code solutions

In [1]:
import math

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## 3.1 Vector dot product: Algebra

### Dot Product: Algebra
$$
a^T b = \langle a, b \rangle = a \cdot b = \sum_{i=0}^n a_i b_i
$$

### Norm Squared
Dot product of a vector with itself is equal to the norm-squared.

$$
a^T a = \left|\textbf{a}\right|^2
$$

### Average
Average describes the most likely value of a component of the vector.

$$
\text{avg}(\textbf{a}) = \frac{1}{n} \textbf{a}^T \textbf{1} 
$$

### RMS
RMS describes the typical absolute value of a component of the vector.

$$
\text{rms}(\textbf{a}) = \frac{\left|\textbf{a}\right|}{\sqrt{n}}
$$

### Norm of Sum
Norm of the sum of two vectors is used to link algebraic and geometric interpretations.

$$
\left|\textbf{a + b}\right|^2 = \left|\textbf{a}\right|^2 + \left|\textbf{b}\right|^2 + 2 a^T b
$$

### Cauchy-Schwartz
Absolute value of the dot product is always less than or equal to the product of the magnitudes.

$$
\left|a^T b\right| \leq \left|\textbf{a}\right| \left|\textbf{b}\right|
$$

## 3.3 Vector dot product: Geometry

### Dot Product: Geometry
$$
a^T b = \cos \theta \left|\textbf{a}\right| \left|\textbf{b}\right|
$$

Note: Entries of a vector should be in consistent units in order to compute angle. If not, then normalize by converting to unit vectors.

### De-Meaned Vector aka Centered
A de-meaned vector has the mean value removed from each component such that the vector has mean of 0 ($\mu = 0$).

$$
\bar{a} = \textbf{a} - \frac{1}{n} \textbf{a}^T \textbf{1}
$$

### Pearson Correlation Coefficient
Pearson correlation coefficient ($\rho$) ranges between $-1$ and $+1$ and describes the linear correlation between a pair of centered vectors.

$$
\rho = \frac{\bar{a}^T \bar{b}}{\left|\bar{a}\right| \left|\bar{b}\right|}
$$

### Relationship Between Dot Product and Angle
$$
\text{obtuse}\\
a^T b < 0 \rightarrow \frac{\pi}{2} < \theta < \pi
$$

$$
\text{orthogonal}\\
a^T b = 0 \rightarrow \theta = \frac{\pi}{2}
$$

$$
\text{acute}\\
a^T b > 0 \rightarrow 0 < \theta < \frac{\pi}{2}
$$

## 3.4 Algebra and Geometry
Summary: Dot product has both algebraic and geometric interpretations.

$$
a^T b = \langle a, b \rangle = a \cdot b = \sum_{i=0}^n a_i b_i = \cos \theta \left|\textbf{a}\right| \left|\textbf{b}\right|
$$

## 3.5 Linear weighted combinations
A linear combination of $n$ vectors where $\textbf{v}_i$ is the _ith_ vector and a vector of scalar weights $\lambda$ where $\lambda_i$ is the _ith_ scalar weight. 

$$
w = \lambda_1 v_1 + \cdots + \lambda_n v_n
$$

Note: Dimension of $v$ vectors could be arbitrary and does not need to equal $n$.  For example: a weighted combination of 3 different 5d vectors.

## 3.6 The outer product
Outer product of a N-dimensional vector $\textbf{a}$ and W-dimensional vector $\textbf{b}$ is the N X W dimensional matrix.

$$
a b^T = 
\begin{bmatrix}a \\ b \\ c \end{bmatrix} 
\begin{bmatrix}d & e & f \end{bmatrix} = 
\begin{bmatrix}ad & ae & af \\ bd & be & bf \\ cd & ce & cf \end{bmatrix}
$$

Note: $a b^T$ is formed from the elementwise products of the rows of $\textbf{a}$ and columns of $\textbf{b}$

Non-vectorized implementation of outer product.

In [2]:
def outer(a, b):
    """
    outer returns the outer product of 1d vectors a and b
    
    :param a: numpy.ndarray  Vector of dimension m.
    :param b: numpy.ndarray  Vector of dimension n.
    :return: numpy.ndarray   Matrix of dimension $m \times n$.
    """
    assert a.ndim == b.ndim == 1
    
    m, n = a.shape[0], b.shape[0]
    abT = np.empty((m, n))
    for i in range(m):
        for j in range(n):
            abT[i, j] = a[i] * b[j]
    return abT

Test of correctness.

In [3]:
a, b = np.random.random((3)), np.random.random((5))
np.testing.assert_almost_equal(outer(a, b), np.outer(a, b), err_msg="outer <> np.outer")

## 3.7 Hadamard multiplication
Hadamard multiplication is the elementwise multiplication of 2 vectors.  Both vectors must be of same dimension.

$$
a \odot b = \begin{bmatrix}a_1 b_1 & \cdots & a_n b_n\end{bmatrix}
$$

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# In numpy, the multiplication operator performs elementwise multiplication.
expected = np.array([4, 10, 18])
np.testing.assert_equal(a * b, expected, err_msg="hadamard")

## 3.8 Cross product
Cross product defined only for 3d vectors. 

$$
a \times b =
\det \begin{bmatrix} 
x & y & z & x & y \\ 
a_x & a_y & a_z & a_x & a_y \\ 
b_x & b_y & b_z & b_x & b_y 
\end{bmatrix} =
\begin{bmatrix}
a_y b_z - a_z b_y \\
a_z b_x - a_x b_z \\
a_x b_y - a_y b_x
\end{bmatrix}
$$

### Cross Product: Perpendicular
Cross product of vectors produces a new vector perpendicular to both.

$$
a \times b = c \rightarrow c \perp a, c \perp b
$$

Note: Direction of the ndew vector is given by the right hand rule.

### Cross Product: Anticommutative
$$
a \times b = -b \times a
$$

### Cross Product: Geometry
$$
\sin \theta \left|\textbf{a}\right| \left|\textbf{b}\right| = \left|a \times b \right|
$$

Note: The geometric relationship of the cross product and innner product are similar.
* Replace cosine with sine.
* Replace product of magnitudes with magnitude of cross product.

## 3.9 Unit vectors
The unit vector $\hat{a}$ is the multiplicative inverse of the vector with it's magnitude.
$$
\hat{a} = \frac{\textbf{a}}{\left|\textbf{a}\right|}
$$


### Magnitude
The unit vector $\hat{a}$ points in the same direction as $\textbf{a}$ but has unit magnitude.

$$
\left|\hat{a}\right| = \textbf{1}
$$


Numpy doesn't have an explicit function to compute unit vector.

In [5]:
def unit(a):
    """
    unit returns the unit vector of a
    
    :param a: numpy.ndarray  Vector.
    :return: numpy.ndarray   Unit vector of a
    """
    assert a.ndim == 1

    ahat = a / np.linalg.norm(a)
    return ahat

Test of correctness.

In [6]:
a = np.array([3, 4, 8])

expected = a / np.sqrt(np.dot(a.T, a))
np.testing.assert_equal(unit(a), expected, err_msg="unit")

## 3.10 Exercises

In [7]:
def vecangle(a, b):
    """
    vecangle returns the angle, in radians, between vectors a and b
    
    :param a: numpy.ndarray  Vector of dimension m.
    :param b: numpy.ndarray  Vector of dimension m.
    :return: float           Angle in radians between a and b.
    """
    assert a.ndim == b.ndim == 1
    assert a.shape[0] == b.shape[0]

    # Convert a and b to unit vectors to avoid domain errors from math.acos.
    return math.acos(np.dot(a/np.linalg.norm(a), b/np.linalg.norm(b)))


a = np.array([1,2,3], dtype=int)
b = np.array([-2,1,0], dtype=int)
theta = vecangle(a, b)
expected = math.pi/2.
np.testing.assert_equal(expected, theta, err_msg="exercise_3a")

a = np.array([10,12,4], dtype=float)
b = np.array([2.5,3,1], dtype=float)
theta = vecangle(a, b)
expected = 0.
np.testing.assert_almost_equal(expected, theta, err_msg="exercise_3b")

a = np.array([-1,-2,3], dtype=int)
b = np.array([3,6,-9], dtype=int)
theta = vecangle(a, b)
expected = math.pi
np.testing.assert_equal(expected, theta, err_msg="exercise_3c")

## 3.12 Code Challenges

> 1. Create a linear weighted combination of 3 vectors. You'll learn in later chapters that linear combinations are most efficiently represented as matrix-vector multiplication, but we'll keep things simple for now. Create 3 $\times$ 5d vectors and a fourth vector that contains the weights for each vector. Then create the weighted sum of those vectors. Next, modify the code to conpute the weighted mixture of 4 $\times$ 5d vectors. What is the relationship between the dimensionality of the to-be-summed vectors, the number of vectors to sum, and the dimensionality of the coefficients vector?

Answer
* Result will have same dimensionality as the input column vectors.
* Weights will have same dimensionality as the number of vectors.

In [8]:
def linear_weighted_combination(V, weights):
    """
    linear_weighted_combination of the matrix of vectors V
    
    :param V: numpy.ndarray        Matrix of concatenated column vectors.
    :param weights: numpy.ndarray  Vector of weights.
    :return: numpy.ndarray         Linear weighted combination.
    """
    assert V.ndim == 2
    assert weights.ndim == 1
    assert V.shape[1] == weights.shape[0]

    return np.sum(weights*V, axis=1)


v1 = np.array([1,1,1,1,1], dtype=float)
v2 = np.array([2,2,2,2,2], dtype=float)
v3 = np.array([3,3,3,3,3], dtype=float)
v4 = np.array([4,4,4,4,4], dtype=float)
V = np.stack((v1,v2,v3,v4), axis=1)
weights = np.array([0.1,0.2,0.3,0.4])
expected = 3.*np.ones(V.shape[0])
print(V)
print(weights)
print(expected)

lwc = linear_weighted_combination(V, weights)
np.testing.assert_equal(lwc, expected, err_msg="4 x 5d")

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[0.1 0.2 0.3 0.4]
[3. 3. 3. 3. 3.]


> 2. Develop a method to use the dot product to compute the average of a set of numbers in a vector.

In [9]:
def average(v):
    """
    average returns the average of the values in the vector v
    
    :param v: numpy.ndarray  Vector.
    :return: float           Average of the values in vector v.
    """
    assert v.ndim == 1
    
    return np.dot(v, np.ones(v.shape[0])) / v.shape[0]


v = np.array([1,2,3,4,5], dtype=int)
mu = average(v)
expected = 3
np.testing.assert_equal(mu, expected, err_msg="average")

v = np.random.random(5)
mu = average(v)
expected = np.average(v)
np.testing.assert_almost_equal(mu, expected, err_msg="average")

> 3. What if some numbers are more important than others. Modify the previous method to use the dot product to compute the weighted mean of a set of numbers.

In [10]:
def weighted_average(v, weights):
    """
    weighted_average returns the weighted average of the values in the vector v
    
    :param v: numpy.ndarray        Vector.
    :param weights: numpy.ndarray  Vector of weights.
    :return: float                 Weighted average of the values in vector v.
    """
    assert v.ndim == 1
    assert v.shape[0] == weights.shape[0]

    return np.dot(v, weights) / np.sum(weights)


v = np.array([1,2,3,4,5], dtype=int)
weights = np.array([3,2,0,2,3])
mu = weighted_average(v, weights)
expected = 3
np.testing.assert_equal(mu, expected, err_msg="weighted_average")

v = np.random.random(5)
weights = np.random.random(5)
mu = weighted_average(v, weights)
expected = np.average(v, weights=weights)
np.testing.assert_almost_equal(mu, expected, err_msg="weighted_average")