# 6 - Matrix Multiplication
- 6.1 Standard multiplication
- 6.2 Multiplication and equations
- 6.3 Multiplication with diagonals
- 6.4 LIVE EVIL
- 6.5 Matrix-vector multiplication
- 6.6 Creating symmetric matrices
- 6.7 Multiply symmetric matrices
- 6.8 Hadamard multiplication
- 6.9 Frobenius dot product
- 6.10 Matrix norms
- 6.11 Matrix asymmetry index
- 6.12 What about matrix division?
- 6.13 Exercises
- 6.14 Answers
- 6.15 Code challenges
- 6.16 Code solutions

Notes, code snippets, and the end of chapter exercises from the book _Linear Algebra: Theory, Intuition, Code_ by Mike X Cohen. 

Find more information about the book on [github](https://github.com/mikexcohen/LinAlgBook) and [amazon](https://www.amazon.com/Linear-Algebra-Theory-Intuition-Code/dp/9083136604).

In [1]:
import math

import numpy as np

## 6.1 Standard Multiplication
Matrix $A \in \mathbb{R}^{M \times N}$ is compatible for multiplication with matrix $B \in \mathbb{R}^{N \times P}$ only when the innermost dimension of $A$ and $B$ are equal.

### 1/ Element Perspective
Interpretation of matrix multiplication as dot products between rows of A and columns of B.

$$
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3} \\
\end{bmatrix}
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2} \\
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1} b_{1,1} + a_{1,2} b_{2,1} + a_{1,3} b_{3,1} & a_{1,1} b_{1,2} + a_{1,2} b_{2,2} + a_{1,3} b_{3,2} \\
a_{2,1} b_{1,1} + a_{2,2} b_{2,1} + a_{2,3} b_{3,1} & a_{2,1} b_{1,2} + a_{2,2} b_{2,2} + a_{2,3} b_{3,2} \\
a_{3,1} b_{1,1} + a_{3,2} b_{2,1} + a_{3,3} b_{3,1} & a_{3,1} b_{1,2} + a_{3,2} b_{2,2} + a_{3,3} b_{3,2} \\
\end{bmatrix}
$$

Notes
- Lower triangle of product $AB$ contains dot products of rows of A whose index is larger than columns of B eg $i \gt j$.
- Upper triangle of product $AB$ contains dot products of columns of B whose index is larger than rows of A eg $j \gt i$.
- Lower and upper triangle interpretations are important for QR decomposition.

### 2/ Layer Perspective
Interpretation of matrix multiplication as sum of outer product of columns of A and rows of B.

$$
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3} \\
\end{bmatrix}
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2} \\
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1} \\
a_{2,1} \\
a_{3,1} \\
\end{bmatrix}
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
\end{bmatrix}
+
\begin{bmatrix}
a_{1,2} \\
a_{2,2} \\
a_{3,2} \\
\end{bmatrix}
\begin{bmatrix}
b_{2,1} & b_{2,2} \\
\end{bmatrix}
+
\begin{bmatrix}
a_{1,3} \\
a_{2,3} \\
a_{3,3} \\
\end{bmatrix}
\begin{bmatrix}
b_{3,1} & b_{3,2} \\
\end{bmatrix}
$$

Notes
- Layer perspective is closely related to spectral theory of matrices which says that any matrix can be represented as  sum of rank-1 matrices.
- Spectral theory of matrices is important for singular value decomposition SVD.

### 3/ Column Perspective
Interpretation of matrix multiplication as linear weighted combination of the columns of A and the columns of B.

$$
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3} \\
\end{bmatrix}
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2} \\
\end{bmatrix}
=
\begin{bmatrix}
 b_{1,1}
 \begin{bmatrix}
 a_{1,1} \\
 a_{2,1} \\
 a_{3,1} \\
 \end{bmatrix}
 +
 b_{2,1}
 \begin{bmatrix}
 a_{1,2} \\
 a_{2,2} \\
 a_{3,2} \\
 \end{bmatrix}
 +
 b_{3,1}
 \begin{bmatrix}
 a_{1,3} \\
 a_{2,3} \\
 a_{3,3} \\
 \end{bmatrix}
 &
 b_{1,2}
 \begin{bmatrix}
 a_{1,1} \\
 a_{2,1} \\
 a_{3,1} \\
 \end{bmatrix}
 +
 b_{2,2}
 \begin{bmatrix}
 a_{1,2} \\
 a_{2,2} \\
 a_{3,2} \\
 \end{bmatrix}
 +
 b_{3,2}
 \begin{bmatrix}
 a_{1,3} \\
 a_{2,3} \\
 a_{3,3} \\
 \end{bmatrix}
\end{bmatrix}
$$

Notes
- The column perspective is useful in statistical infererence where the columns of the left matrix A contain the predictors and the columns of the right matrix B contain the model coefficients or weights. The product of AB is the prediction from the model.

### 4/ Row Perspective
Interpretation of matrix multiplication as linear weighted combination of the rows of A and the rows of B.

$$
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3} \\
\end{bmatrix}
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2} \\
\end{bmatrix}
=
\begin{bmatrix}
 a_{1,1}
 \begin{bmatrix}
 b_{1,1} & b_{1,2}
 \end{bmatrix}
 +
 a_{1,2}
 \begin{bmatrix}
 b_{2,1} & b_{2,2}
 \end{bmatrix}
 +
 a_{1,3}
 \begin{bmatrix}
 b_{3,1} & b_{3,2}
 \end{bmatrix} \\
 a_{2,1}
 \begin{bmatrix}
 b_{1,1} & b_{1,2}
 \end{bmatrix}
 +
 a_{2,2}
 \begin{bmatrix}
 b_{2,1} & b_{2,2}
 \end{bmatrix}
 +
 a_{2,3}
 \begin{bmatrix}
 b_{3,1} & b_{3,2}
 \end{bmatrix} \\
 a_{3,1}
 \begin{bmatrix}
 b_{1,1} & b_{1,2}
 \end{bmatrix}
 +
 a_{3,2}
 \begin{bmatrix}
 b_{2,1} & b_{2,2}
 \end{bmatrix}
 +
 a_{3,3}
 \begin{bmatrix}
 b_{3,1} & b_{3,2}
 \end{bmatrix} \\
\end{bmatrix}
$$

Notes
- The row perspective is useful in principal component analysis (PCA) where the rows of the right matrix B contain data (observations in rows and features in columns) and the rows of the left matrix A contain weights for combining the features.  The product of AB is the principal component scores.

In [2]:
def mmult_as_dot(A,B):
    """
    mmult_as_dot returns the product AB as dot products of rows of A and columns of B

    :param A: numpy.ndarray  Matrix A
    :param B: numpy.ndarray  Matrix B
    :return: numpy.ndarray   Matrix product AB
    """
    assert A.shape[1] == B.shape[0]
    
    m, n, p = A.shape[0], A.shape[1], B.shape[1]
    AB = np.zeros((m,p))
    for i in range(m):
        for j in range(p):
            AB[i,j] = np.dot(A[i,:], B[:,j])
    return AB


m, n, p = 4, 3, 2
A = np.random.random((m,n))
B = np.random.random((n,p))
AB = mmult_as_dot(A,B)
expected = A @ B
np.testing.assert_almost_equal(AB, expected, err_msg="mmult_as_dot")

In [3]:
def mmult_as_outer(A,B):
    """
    mmult_as_outer returns the product AB as sum of outer products of columns of A and rows of B

    :param A: numpy.ndarray  Matrix A
    :param B: numpy.ndarray  Matrix B
    :return: numpy.ndarray   Matrix product AB
    """
    assert A.shape[1] == B.shape[0]
    
    m, n, p = A.shape[0], A.shape[1], B.shape[1]
    AB = np.zeros((m,p))
    for k in range(n):
        AB += np.outer(A[:,k], B[k,:])
    return AB


m, n, p = 4, 3, 2
A = np.random.random((m,n))
B = np.random.random((n,p))
AB = mmult_as_outer(A,B)
expected = A @ B
np.testing.assert_almost_equal(AB, expected, err_msg="mmult_as_outer")

In [4]:
def mmult_as_col(A,B):
    """
    mmult_as_col returns the product AB as linear weighted combination of columns of A and B

    :param A: numpy.ndarray  Matrix A
    :param B: numpy.ndarray  Matrix B
    :return: numpy.ndarray   Matrix product AB
    """
    assert A.shape[1] == B.shape[0]
    
    m, n, p = A.shape[0], A.shape[1], B.shape[1]
    AB = np.empty((m,p))
    for k in range(p):
        AB[:,k] = A @ B[:,k]
    return AB


m, n, p = 4, 3, 2
A = np.random.random((m,n))
B = np.random.random((n,p))
AB = mmult_as_col(A,B)
expected = A @ B
np.testing.assert_almost_equal(AB, expected, err_msg="mmult_as_col")

In [5]:
def mmult_as_row(A,B):
    """
    mmult_as_row returns the product AB as linear weighted combination of rows of A and B

    :param A: numpy.ndarray  Matrix A
    :param B: numpy.ndarray  Matrix B
    :return: numpy.ndarray   Matrix product AB
    """
    assert A.shape[1] == B.shape[0]
    
    m, n, p = A.shape[0], A.shape[1], B.shape[1]
    AB = np.empty((m,p))
    for i in range(m):
        AB[i,:] = A[i,:] @ B
    return AB


m, n, p = 4, 3, 2
A = np.random.random((m,n))
B = np.random.random((n,p))
AB = mmult_as_row(A,B)
expected = A @ B
np.testing.assert_almost_equal(AB, expected, err_msg="mmult_as_row")

## 6.2 Multiplication and equations
When performing matrix algebra to both sides of an equation, then matrix order eg pre-multiplication or post-multiplication must be preserved.

$$
\begin{align}
A &= A \\
AB &= AB \quad \text{post-multiply} \\
BA &= BA \quad \text{pre-multiply} \\
\end{align}
$$

## 6.3 Multiplication with diagonals
Pre-multiplication with a diagonal matrix scales the rows of the right matrix by diagonal elements.

$$
\begin{bmatrix}
k_1 & 0 & 0 \\
0 & k_2 & 0 \\
0 & 0 & k_3 \\
\end{bmatrix}
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix} =
\begin{bmatrix}
k_1 a & k_1 b & k_1 c \\
k_2 d & k_2 e & k_2 f \\
k_3 g & k_3 h & k_3 i \\
\end{bmatrix}
$$

Post-multiplication with a diagonal matrix scales the columns of the left matrix by diagonal elements.

$$
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix}
\begin{bmatrix}
k_1 & 0 & 0 \\
0 & k_2 & 0 \\
0 & 0 & k_3 \\
\end{bmatrix} =
\begin{bmatrix}
k_1 a & k_2 b & k_3 c \\
k_1 d & k_2 e & k_3 f \\
k_1 g & k_2 h & k_3 i \\
\end{bmatrix}
$$

Multiplication of two diagonal matrices is the product of the diagonals.

$$
\begin{bmatrix}
a & 0 & 0 \\
0 & b & 0 \\
0 & 0 & c \\
\end{bmatrix}
\begin{bmatrix}
d & 0 & 0 \\
0 & e & 0 \\
0 & 0 & f \\
\end{bmatrix} =
\begin{bmatrix}
a d & 0 & 0 \\
0 & b e & 0 \\
0 & 0 & c f \\
\end{bmatrix}
$$

## 6.4 LIVE EVIL
An operation applied to the product of matrices is equal to the product of the operation applied to each matrix but in reverse order.

$$
\begin{align}
(A_1 A_2 \cdots A_N)^T &= A_N^T \cdots A_2^T A_1^T \\
(A_1 A_2 \cdots A_N)^{-1} &= A_N^{-1} \cdots A_2^{-1} A_1^{-1} \\
\end{align}
$$

## 6.5 Matrix-vector multiplication
Matrix-vector multiplication always produces a vector.
- This is the connection between linear transformations that underpin computer graphics.

## 6.6 Creating symmetric matrices
Methods for creating symmetric matrices from a non-symmetric matrix.

Notes
- Symmetric matrix implies $C = C^T$.
- In general, the matrix produced from Method 1 will not be equal to matrix produced from Method 2 eg not unique.

### Method 1/ Additive
$C = \frac{1}{2} (A^T + A)$

Notes
- A must be square

### Method 2/ Multiplicative
$C = A^T A$

Notes
- C will be square, even if A is not

## 6.8 Hadamard multiplication
Hadamard multiplication is the elementwise multiplication of 2 matrices. Both matrics must be of same dimension.

$$
C = A \odot B \implies c_{i,j} = a_{i,j} b_{i,j}
$$

Notes
* Unlike matrix multiplication, Hadamard multiplication is commutative $A \odot B = B \odot A$

## 6.9 Frobenius dot product
Frobenius dot product is the sum of the elementwise multiplication of 2 matrices. Both matrices must be of same dimension.

$$
\langle A, B \rangle_{F} = \sum_i^M \sum_j^N a_{i,j} b_{i,j} = \sum A \odot B
$$

Notes
* Frobenius dot product is equivalent to the sum of the elements of the Hadamard matrix.
* Frobenius dot product is used as a measure of distance or similarity between two matrices.

### Alternate Definition
$$
\langle A, B \rangle_{F} = \text{tr}(A^T B)
$$

In [6]:
def frob(A,B):
    """
    frob returns the frobenius dot product between matrices A and B

    :param A: numpy.ndarray  Matrix A
    :param B: numpy.ndarray  Matrix B
    :return: float           Frobenius dot product
    """
    assert A.shape == B.shape
    
    return np.sum(A * B)


m, n = 4, 3
A = np.random.random((m,n))
B = np.random.random((m,n))
ABF = frob(A,B)
expected = np.trace(A.T @ B)
np.testing.assert_almost_equal(ABF, expected, err_msg="frob")

## 6.10 Matrix norms
There exists many different kinds of matrix norms.  Some of them are listed below.

Frobenius matrix norm aka _L2 norm_.

$$
|| A ||_F = \sqrt{ \sum_i^M \sum_j^N a_{i,j}^2 }
$$

Properties
* Frobenius matrix norm can be used to measure distance between matrices $|| A - B ||_F$

In [7]:
def distL2(A,B):
    """
    distL2 returns distance between two matrices A and B using the L2 norm

    :param A: numpy.ndarray  Matrix A
    :param B: numpy.ndarray  Matrix B
    :return: float           Frobenius dot product
    """
    assert A.shape == B.shape
    
    return math.sqrt(np.sum(np.square(A-B)))


m, n = 4, 3
A = np.random.random((m,n))
B = np.random.random((m,n))
dAB = distL2(A,B)
expected = np.linalg.norm(A-B, 'fro')
np.testing.assert_almost_equal(dAB, expected, err_msg="distL2")

## 6.11 Matrix asymmetry index
Every square matrix $A$ can be expressed as the sum of a symmetric matrix $A_s$ and skew-symmetric matrix $A_k$.

$$
A = A_s + A_k
$$

Notes
- Skew-symmetric implies $C = -C^T$ (entries along diagonals must be 0).
- Think of the skew-symmetric matrix $A_k$ as the residual. When this matrix is small, then the original matrix is relatively symmetric.

### Skew-Symmetric Matrix, $A_k$
A skew-symmetric matrix is formed by re-arranging the terms in the additive method for constructing a symmetric matrix.

$A_k = (A - A^T) / 2$

### Symmetric Matrix, $A_s$

$A_s = A - A_k$

### Matrix Asymmetry Index, $A_\sigma$
Matrix asymetry index describes how symmetric a matrix is.
- Values near 0 indicate the matrix is (nearly) symmetric.
- Values near 1 indicate the matrix is (nearly) skew-symmetric.

$$
A_\sigma = \frac{||A_k||_F^2}{||A||_F^2}
$$

Notes
- Invert the value of index to obtain a symmetry index $1 - A_\sigma$.

In [8]:
m = 4
A = np.random.random((m,m))

Asym = 0.5*(A.T + A)
Assym = 0.5*(A - A.T)
Asum = Asym + Assym
np.testing.assert_almost_equal(Asum, A, err_msg="matrix as sum of symmetric and skew-symmetric")

## 6.15 Code Challenges

> 2. Generate a 4 x 4 diagonal matrix and a 4 x 4 dense matrix of random numbers. Compute both standard and Hadamard multiplication between them. You already know that the resulting product matrices are not the same, but what about the diagonals of those two product matrices?

In [9]:
A = np.diag(np.arange(1, 5, dtype=float))
B = np.random.random((4,4))
AB = A @ B
ABpt = A * B

np.testing.assert_almost_equal(np.diag(AB), np.diag(ABpt), 
                               err_msg="diagonals of matrix and pointwise product are equal")
print("AB\n", AB)
print("ABpt\n", ABpt)

AB
 [[0.34413881 0.05851533 0.25849147 0.76693329]
 [0.31091244 0.88084554 0.93684188 0.19550658]
 [0.23027404 0.44177244 1.30454044 2.67610962]
 [3.53445122 0.54135024 1.28286597 2.36713607]]
ABpt
 [[0.34413881 0.         0.         0.        ]
 [0.         0.88084554 0.         0.        ]
 [0.         0.         1.30454044 0.        ]
 [0.         0.         0.         2.36713607]]


> 3. Consider $C_1 = (A^T + A) / 2$ and $C_2 = A^T A$ for some square non-symmetric matrix A. $C_1$ and $C_2$ are both symmetric and both formed from the same matrix, yet in general $C_1 \neq C_2$. Interestingly, if $A$ is a diagonal matrix with all non-negative values, then $C_1 = C_2^{\frac{1}{2}}$. Show this in code using random numbers, and then explain why you get the result.

In [10]:
def sym_add(A):
    """
    sym_add returns a symmetric matrix from A using the additive method

    :param A: numpy.ndarray  Matrix A
    :return: numpy.ndarray   Symmetric matrix A = A^T
    """
    return (A + A.T) / 2.


def sym_mult(A):
    """
    sym_mult returns a symmetric matrix from A using the multiplicative method

    :param A: numpy.ndarray  Matrix A
    :return: numpy.ndarray   Symmetric matrix A = A^T
    """
    return A @ A.T


# Since A is a diagonal matrix, A @ A.T contains the square of the diagonals.
A = np.diag(np.random.random(4))
C1 = sym_add(A)
C2 = sym_mult(A)
np.testing.assert_almost_equal(C1, np.sqrt(C2), err_msg="C_1 = C_2^(1/2)")

> 4. Let's explore the Cauchy-Schwartz inequality. Generate a random matrix $A$ and a random vector $v$. Show that $||Av|| \leq ||A||_F ||v||$. 

In [11]:
A = np.random.random((4,4))
v = np.random.random(4)

Avnorm = np.linalg.norm(A @ v)
Anorm = np.linalg.norm(A, 'fro')
vnorm = np.linalg.norm(v)
CS = bool(Avnorm <= Anorm * vnorm)
np.testing.assert_equal(CS, True, err_msg="Cauchy-Schwartz inequality")