# 8 - Matrix Spaces
- 8.1 Column space of a matrix
- 8.2 Column space: $A$ and $AA^T$
- 8.3 Determining whether $v \in C(A)$
- 8.4 Row space of a matrix
- 8.5 Row spaces of $A$ and $A^TA$
- 8.6 Null space of a matrix
- 8.7 Geometry of the null space
- 8.8 Orthogonal subspaces
- 8.9 Matrix space orthogonalities
- 8.10 Dimensionalities of matrix spaces
- 8.11 More on $Ax = b$ and $Ay = 0$
- 8.12 Exercises
- 8.13 Answers
- 8.14 Code challenges
- 8.15 Code solutions

In [1]:
import numpy as np
import scipy.linalg as spla

## 8.1 Column space of a matrix, $C(\textbf{A})$
Column space is the subspace spanned by all columns of a matrix $\textbf{A}$.

$$
C(\textbf{A}) = \text{span}(a_1, \dots, a_n)
$$

Notes
- Vectors that span a subspace must also be linearly independent to be considered as a basis for the subspace.
    - Not all column spaces form a basis.
- The dimensionality of the column space is given by the number of **rows** in the matrix.
    - The column space of $M \times N$ matrix is in $\mathbb{R^M}$.

## 8.2 Column space: $A$ and $AA^T$
Column space of matrix and linear weighted combination (LWC) of columns of $\textbf{A}$ are equal.

$$
C(A) = C(AA^T)
$$

Notes
- Based on the column interpretation of matrix multiplication in which $A A^T$ is linear weighted combination of the columns of $A$.
- Proof: Linear combination of a column of vectors always stays in the same subspace.

## 8.3 Determining whether $v \in C(A)$
The vector $\textbf{v}$ is in the column space of $\textbf{A}$ when a linear weighted combination (LWC) of the columns of $\textbf{A}$ produce $\textbf{v}$.

$$
Ax = v \rightarrow v \in C(A)
$$

Notes
- Proof: IFF $\text{rank}(\textbf{A}) = \text{rank}(\textbf{A}|\textbf{v})$ then $\textbf{v}$ is in the span of $\textbf{A}$. 

## 8.4 Row space of a matrix, $R(\textbf{A})$
Row space is the subspace spanned by all rows of a matrix and denoted as $R(\textbf{A})$.
- Row space equals the column space of the transpose $R(A) = C(A^T)$.

Notes
- Vectors that span a subspace must also be linearly independent to be considered as a basis for the subspace.
    - Not all row spaces form a basis.
- The dimensionality of the row space is given by the number of **columns** in the matrix.
    - The row space of $M \times N$ matrix is in $\mathbb{R^N}$.

## 8.5 Row spaces of $A$ and $A^TA$
Row space of matrix and linear weighted combination (LWC) of rows of $\textbf{A}$ are equal. 

$$
R(A) = R(A^TA)
$$

### Determining whether $u \in R(A)$
The vector $\textbf{u}$ is in the row space of $\textbf{A}$ when a linear weighted combination (LWC) of the rows of $\textbf{A}$ produce $\textbf{u}$.

$$
w^T A = u^T \rightarrow u \in R(A)
$$

## 8.6 Null space of a matrix, $N(\textbf{A})$
Null space of a matrix $N(\textbf{A})$ is the subspace containing all of the vectors that satisfy the equation $A y = 0$ where $y \neq 0$.

Notes
- Null space refers to the linear combination of the columns of $A$.
- Full rank matrices have an empty null space.
- Reduced rank have a non-empty null space.
- The vector $\textbf{y}$ is not necessarily unique.

### Left Null Space
Left null space of a matrix is the subspace containing all of the vectors that satisfy the equation $y^T A = 0^T$ where $y \neq 0$.

Notes
- Left null space refers to the linear combination of the rows of $A$.
- IFF $A = A^T$, then the left null space is equivalent to the null space of the transpose $N(A) = N(A^T)$.

In [2]:
# Find the null space of the matrix.
A = np.array([[1,2,3],[3,1,4],[4,4,8]], dtype=int)
y = spla.null_space(A)

print("A\n", A)
print("y\n", y)

# Check whether Ay = 0.
np.testing.assert_almost_equal(A @ y, np.zeros((A.shape[0],y.shape[1])))

A
 [[1 2 3]
 [3 1 4]
 [4 4 8]]
y
 [[-0.57735027]
 [-0.57735027]
 [ 0.57735027]]


## 8.7 Geometry of the null space
1. Mental model of the null space as a subspace in which the product $Ay$ produces a zero vector.
2. The reduced rank matrix $A$ can still have some vector $x$ such that $Ax \neq 0$.

## 8.8 Orthogonal subspaces
Subspaces $\textbf{S}$ and $\textbf{M}$ are orthogonal subspaces if $v \in S$ and $w \in M$ and $v \perp w$.

Notes
- An example of an orthogonal subspace is a plane in $\mathbb{R}^3$ and a vector perpindicular to the plane.
- Recall that subspace must contain the zero vector $\textbf{0}$.

### Orthogonal Complements
Any ambient space $\mathbb{R}^N$ can be decomposed into subspaces $W$ and $V$ such that $W \cup V$ spans all of $\mathbb{R}^N$ and $W \perp V$.

Notes
- Mutually orthogonal means that any vector cannot be both in $\textbf{W}$ and in $\textbf{V}$

## 8.9 Matrix space orthogonalities
For any $M \times N$ matrix the column space and left null space are orthogonal complements $C(A) \cup N(A^T) \iff \mathbb{R}^M$.

For any $M \times N$ matrix the row space and null space are orthogonal complements $R(A) \cup N(A) \iff \mathbb{R}^N$ 

(_inverse of previous statement_).

Notes
- Every vector in $\mathbb{R}^M$ is either in the column space or left null space, but not both.
- The orthogonal complement spans all of $\mathbb{R}^M$.
- A full rank matrix spans all of $\mathbb{R}^M$ and the left null space will be empty.

### Finding a Basis
Find a basis for the column space by taking the linearly independent column vectors of the matrix.

Example
- The matrix $A = \begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix}$ has $\text{rank}(A) = 1$ and thus the vector $\begin{bmatrix} 1 \\ 2 \end{bmatrix}$ is a basis for the column space.

## 8.10 Dimensionalities of matrix spaces
$$
\begin{align}
\text{dim}(C(\textbf{A})) + \text{dim}(N(\textbf{A}^T)) &= M \\
\text{dim}(R(\textbf{A})) + \text{dim}(N(\textbf{A})) &= N \\
\end{align}
$$

## 8.11 More on $Ax = b$ and $Ay = 0$

### $Ax = b$
Answers the question
> Is there a weighted combination of the columns of A that produces the vector b with the weights from vector x?

- Equation has an exact solution when b is in the column space of A eg $b \in C(A)$.
- There also exists an approximate solution $\hat{b} \in C(A)$ that is as close as possible to exact solution $b$.

### $Ay = 0$
Answers the question
> Is there a weighted combination of the columns of A that produces the zero vector with the weights of the nonzero vector y?

- Related to the solution of the characteristic equation $(A - \lambda I) y = 0$ where $\lambda$ represents the eigenvalues and $y$ the eigenvectors.
    - Recall that shifting the matrix by a multiple of the identity matrix improves the conditioning of the resulting matrix.

## 8.14 Code challenges

> 1. Create two $4 \times 4$ matrices with rank=3. Call those matrices $A$ and $B$. Then find a vector $n$ in the null space of $A$. Show that $BAn$ is the zeros vector while $ABn$ is not.

In [3]:
def rank(m, n, r):
    """
    rank returns a matrix of random values with dimensions m \times n and rank r 

    :param m: int            Number of rows.
    :param n: int            Number of columns.
    :param r: int            Rank.
    :return: numpy.ndarray   Matrix with dimensions m \times n and rank r.
    """
    assert r <= m and r <=n

    A = np.random.random((m, r))
    B = np.random.random((r, n))
    return A @ B


A = rank(4, 4, 3)
B = rank(4, 4, 3)
n = spla.null_space(A)

# Verify that BAn is the zeros vector since An = 0.
np.testing.assert_almost_equal(B @ A @ n, np.zeros((n.size, 1)))

# Verify that ABn is not the zeros vector since Bn != 0.
np.testing.assert_equal(np.not_equal(A @ B @ n, np.zeros((n.size, 1))), True)

> 1. The goal of this code challenge is to confirm the subspace dimensionalities expressed in section 8.10. Create a $16 \times 11$ matrix with rank=9.  Determine the dimensionalities of the left and right nullspace. Confirm that the dimensionality of the column space and left null space is equal to the number of rows. Confirm that the dimensionality of the row space and null space is equal to the number of columns.

In [4]:
m, n, r = 16, 11, 9
A = rank(m, n, r)

dim_left_nullspace = spla.null_space(A.T).shape[1]
dim_right_nullspace = spla.null_space(A).shape[1]
rankA = np.linalg.matrix_rank(A)

# Verify dim(C(A)) + dim(N(A^T)) = M.
np.testing.assert_equal(rankA + dim_left_nullspace, m)

# Verify dim(R(A)) + dim(N(A)) = N.
np.testing.assert_equal(rankA + dim_right_nullspace, n)